services:
  postgres:
    image: postgres:16
    env_file:
      - .env_db
    networks:
      - conn
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  server:
    build: .
    ports:
      - "8000:8000"
    networks:
      - conn
    env_file:
      - .env_app
    command: >
      sh -c "alembic revision --autogenerate && alembic upgrade head && uv run src/main.py"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - postgres-db-volume:/app/model

networks:
  conn:
    driver: bridge


volumes:
  postgres-db-volume:
